package com.hibernate.entity;
// Generated 2017-3-23 19:40:30 by Hibernate Tools 5.2.1.Final

import java.util.Date;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Integer orderId;
	private Staff staff;
	private Stationery stationery;
	private int quantity;
	private Date date;

	public Orders() {
	}

	public Orders(int quantity, Date date) {
		this.quantity = quantity;
		this.date = date;
	}

	public Orders(Staff staff, Stationery stationery, int quantity, Date date) {
		this.staff = staff;
		this.stationery = stationery;
		this.quantity = quantity;
		this.date = date;
	}
	public Orders(Integer orderId,Staff staff, Stationery stationery, int quantity, Date date) {
		this.orderId = orderId;
		this.staff = staff;
		this.stationery = stationery;
		this.quantity = quantity;
		this.date = date;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}
	public Staff getStaff() {
		return this.staff;
	}
	public void setStaff(Staff staff) {
		this.staff = staff;
	}
	public Stationery getStationery() {
		return this.stationery;
	}
	public void setStationery(Stationery stationery) {
		this.stationery = stationery;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
