package citi.hibernate.entity;
// Generated 2017-3-23 13:03:30 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int orderId;
	private Staff staff;
	private Stationery stationery;
	private int quantity;
	private Date date;

	public Orders() {
	}

	public Orders(int orderId, int quantity, Date date) {
		this.orderId = orderId;
		this.quantity = quantity;
		this.date = date;
	}

	public Orders(int orderId, Staff staff, Stationery stationery, int quantity, Date date) {
		this.orderId = orderId;
		this.staff = staff;
		this.stationery = stationery;
		this.quantity = quantity;
		this.date = date;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Stationery getStationery() {
		return this.stationery;
	}

	public void setStationery(Stationery stationery) {
		this.stationery = stationery;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
