package citi.hibernate.entity;
// Generated 2017-3-23 13:03:30 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * System generated by hbm2java
 */
public class System implements java.io.Serializable {

	private int systemId;
	private String note;
	private Date deadline;
	private Date date;
	private String operator;

	public System() {
	}

	public System(int systemId, Date date, String operator) {
		this.systemId = systemId;
		this.date = date;
		this.operator = operator;
	}

	public System(int systemId, String note, Date deadline, Date date, String operator) {
		this.systemId = systemId;
		this.note = note;
		this.deadline = deadline;
		this.date = date;
		this.operator = operator;
	}

	public int getSystemId() {
		return this.systemId;
	}

	public void setSystemId(int systemId) {
		this.systemId = systemId;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

}
