// default package
// Generated 2017-4-3 11:19:10 by Hibernate Tools 5.2.1.Final

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer adminNo;
	private String name;
	private String password;

	public Admin() {
	}

	public Admin(String name, String password) {
		this.name = name;
		this.password = password;
	}

	public Integer getAdminNo() {
		return this.adminNo;
	}

	public void setAdminNo(Integer adminNo) {
		this.adminNo = adminNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
