package com.hibernate.entity;
// Generated 2017-3-23 19:40:30 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Salary generated by hbm2java
 */
public class Salary implements java.io.Serializable {

	private int salaryNo;
	private Integer staffNo;
	private Date date;
	private Boolean isSent;
	private Boolean isReceived;
	private Integer basicSalary;
	private Integer bonus;
	private Integer reduce;
	private Integer allowance;

	public Salary() {
	}

	public Salary(int salaryNo) {
		this.salaryNo = salaryNo;
	}

	public Salary(int salaryNo, Integer staffNo, Date date, Boolean isSent, Boolean isReceived, Integer basicSalary,
			Integer bonus, Integer reduce, Integer allowance) {
		this.salaryNo = salaryNo;
		this.staffNo = staffNo;
		this.date = date;
		this.isSent = isSent;
		this.isReceived = isReceived;
		this.basicSalary = basicSalary;
		this.bonus = bonus;
		this.reduce = reduce;
		this.allowance = allowance;
	}

	public int getSalaryNo() {
		return this.salaryNo;
	}

	public void setSalaryNo(int salaryNo) {
		this.salaryNo = salaryNo;
	}

	public Integer getStaffNo() {
		return this.staffNo;
	}

	public void setStaffNo(Integer staffNo) {
		this.staffNo = staffNo;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Boolean getIsSent() {
		return this.isSent;
	}

	public void setIsSent(Boolean isSent) {
		this.isSent = isSent;
	}

	public Boolean getIsReceived() {
		return this.isReceived;
	}

	public void setIsReceived(Boolean isReceived) {
		this.isReceived = isReceived;
	}

	public Integer getBasicSalary() {
		return this.basicSalary;
	}

	public void setBasicSalary(Integer basicSalary) {
		this.basicSalary = basicSalary;
	}

	public Integer getBonus() {
		return this.bonus;
	}

	public void setBonus(Integer bonus) {
		this.bonus = bonus;
	}

	public Integer getReduce() {
		return this.reduce;
	}

	public void setReduce(Integer reduce) {
		this.reduce = reduce;
	}

	public Integer getAllowance() {
		return this.allowance;
	}

	public void setAllowance(Integer allowance) {
		this.allowance = allowance;
	}

}
