// default package
// Generated 2017-4-3 11:19:10 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private int staffNo;
	private String name;
	private String position;
	private String identityId;
	private String sex;
	private Date birthday;
	private String telephone;
	private Date date;
	private String password;

	public Staff() {
	}

	public Staff(int staffNo) {
		this.staffNo = staffNo;
	}

	public Staff(int staffNo, String name, String position, String identityId, String sex, Date birthday,
			String telephone, Date date, String password) {
		this.staffNo = staffNo;
		this.name = name;
		this.position = position;
		this.identityId = identityId;
		this.sex = sex;
		this.birthday = birthday;
		this.telephone = telephone;
		this.date = date;
		this.password = password;
	}

	public int getStaffNo() {
		return this.staffNo;
	}

	public void setStaffNo(int staffNo) {
		this.staffNo = staffNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getIdentityId() {
		return this.identityId;
	}

	public void setIdentityId(String identityId) {
		this.identityId = identityId;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
